### ISSUE TITLE
cannot find a way how to authenticate POST request

### ISSUE THREAD

**Issue by IowaIowa** [zamzterz/Flask-pyoidc#101] opened 2021-01-28 06:33 UTC
Hi, I am having problems with authentication of POST requests using flask-pyoidc. I have got such code snippet:
```
@app.route("/send", methods = ['POST'])
@auth.oidc_auth("default")
def process_submit():
```
but the authetication request is sent to server by GET method and server then redirects me also with GET method. How should I proceed please?

**Comment by zamzterz** [comment] 2021-01-28 15:10
This framework will always try to authenticate user by redirecting them via the browser to the configured identity provider.
So I'm not sure how you're trying to use it, could you please clarify?

**Comment by IowaIowa** [comment] 2021-01-28 15:32
my point is that I am trying to authenticate POST request endpoint, but then the framework sends GET authentication request and server after succesfull authentication then redirects me also with GET request to "/send" endpoint and then I get 405 - method not allowed error, because the endpoint is expectin POST

**Comment by IowaIowa** [comment] 2021-01-28 15:42
![auth](https://user-images.githubusercontent.com/63630221/106161823-b8923180-6187-11eb-873b-33ca9eb98cc0.png)

**Comment by zamzterz** [comment] 2021-01-28 18:21
This framework does not really support authenticating API requests - it's more intended to do the initial login of the user and gives you a user session (stored in `flask.session`). You should receive that session if the POST request originates from the browser after the user has authenticated, so then you can determine if the user is logged-in or not.

But generally the auth decorator is applied to a separate login endpoint, supporting GET requests.

**Comment by rajaramanram** [comment] 2021-03-11 06:59
hi, i didn't able to get token from flask user session after login , could anyone please help

**Comment by infohash** [comment] 2022-01-23 07:05
I've reproduced this bug. If you are making a POST request from your web app and your session is empty or expired, the request to the post endpoint is redirected to the Identity Provider.

Then this line redirects back to the called endpoint URL.

https://github.com/zamzterz/Flask-pyoidc/blob/01dfa65c241e89b1daf5987cb78daa403c2d4f94/src/flask_pyoidc/flask_pyoidc.py#L132

But `flask.redirect` redirects using the GET method. See [Why doesn't HTTP have POST redirect?](https://softwareengineering.stackexchange.com/q/99894). But the endpoint it's being redirected to only supports POST method which throws 405 after redirecting back.

**Comment by zamzterz** [comment] 2022-01-23 13:14
Good catch @infohash!

Seems like this is due to app view misconfiguration, so I'll close it.

**Closed by zamzterz** 2022-01-23 13:14 UTC

**Comment by infohash** [comment] 2022-01-23 13:23
In my test app, I've configured the post endpoint correctly. It's a design problem and we need to address it. We should not redirect the user if it was a post request. Instead we need to find a solution how to resend the post request after authenticating with the Identity Provider.

**Comment by zamzterz** [comment] 2022-01-23 13:50
I think that would be outside the scope of this extension, as the final redirect is always a `GET` from the provider back and it doesn't make sense for this extension to do it differently (exactly for the reasons specified in the link above).

It should be possible to work around - either by handling the final redirect in the same endpoint (which in that case must support/allow `GET` as well), or by configuring an `error_view` which redirects back to login in such cases.

It's not perfect, but as this extension works right now - with automatic redirect to the provider if no session exists - the decorators might not be fully usable on POST endpoints.

**Comment by infohash** [comment] 2022-01-24 10:53
`error_view` only runs when `_handle_authentication_response` returns `_handle_error_response` but because the error is thrown by the post endpoint after `redirect(destination)` is returned, it is outside the scope of error_view.

How other extensions handle this situation? Our design should be to redirect the app to the base URL if it was a post/put/patch/delete request else redirect to `destination`.

**Comment by zamzterz** [comment] 2022-01-26 12:23
You're right - I didn't look into details, just responded from the top of my head. 🙂 

Thinking about it some more though, this definitely sounds like a use case better handled by the app: the `oidc_auth` decorator (as it is right now) doesn't really make sense to use on a POST endpoint.
Instead that POST endpoint should check if there exists a `UserSession`. If it doesn't then it can decide what to do, either redirect to base URL or login URL or show error message (like "Not allowed for non-logged-in users.").

**Comment by enkelli** [comment] 2022-01-26 12:45
> Instead that POST endpoint should check if there exists a UserSession. If it doesn't then...

Tip: I'm using [valid_access_token()](https://github.com/zamzterz/Flask-pyoidc/blob/3733c6ea057a32b284b61d47b30f3c83bfbf8b95/src/flask_pyoidc/flask_pyoidc.py#L280) in this case :) It checks if user session. Moreover, it also checks if it is expired and if it is, it requests new access token (works even in POST requests).

**Comment by infohash** [comment] 2022-01-27 17:59
@enkelli What do you do if `valid_access_token` returns None?

**Comment by enkelli** [comment] 2022-01-28 08:02
Then I redirect user to login page. There is nothing else to do. It should be a corner case.

**Comment by infohash** [comment] 2022-04-03 21:56
This is how I solved it:

```python
def handle_unauthenticated_request(oidc_auth_decorator):

    def wrapper():

        if auth._check_authorization_header(flask.request):
            return oidc_auth_decorator()
        if not auth.valid_access_token():
            flask.abort(401)
        return oidc_auth_decorator()

    return wrapper

@blueprint.post('/form')
@handle_unauthenticated_request
@auth.oidc_auth('default')
def form_submission():

    web_form = Form()
    if web_form.validate_on_submit():
        if request.form:
            form_data = request.form
            return Response(status=204)
```

This returns 401 if not authenticated and also preserves the form elements. Through javascipt, you can authenticate the user in a separate tab.
